### ISSUE TITLE
服务端多用户登录

### ISSUE THREAD

**Issue by qiuhongxiao** [yaphone/itchat4j#104]
我把这个项目整合到一个http服务里，当一个用户请求后扫码登录没问题，另外一个用户再请求，前面一个用户就会被下线（syncCheck检测到退出），不知道是代码问题还是微信的限制,   我已经把Core改为支持多线程，服务端能区分不同用户用的是哪个Core,

**Comment by koqiui** [comment]
整个框架仅仅是移植自python版的itchat，就是只支持一个微信用户，希望作者总体改造支持多用户登录，这样更有应用价值，否则基本没什么价值
