### ISSUE TITLE
MessageTools.sendPicMsgByUserId暂时不能使用

### ISSUE THREAD

**Issue by mdjava** [yaphone/itchat4j#17]
webWxUploadMedia 错误：syntax error, pos 1, json : <!DOCTYPE html>...，好像是文件上传有问题

**Comment by yaphone** [comment]
多谢，已修正，BUG原因是之前做了一次调整，导致图片发送时参数不全。
祝使用愉快！

**Comment by mdjava** [comment]
BaseRequest 感觉跟这个没有关系！还是错误，微信直接返回错误页面！

**Comment by mdjava** [comment]
private static JSONObject webWxUploadMedia(String filePath,String userId) {
		File f = new File(filePath);
		if (!f.exists() && f.isFile()) {
			LOG.info("file is not exist");
			return null;
		}
		
_//		String url = String.format(URLEnum.WEB_WX_UPLOAD_MEDIA.getUrl(), core.getLoginInfo().get("fileUrl"));_
		**String url = String.format(URLEnum.WEB_WX_UPLOAD_MEDIA.getUrl(), "https://file.wx.qq.com/cgi-bin/mmwebwx-bin");**
**文件上传的域名及路径有问题**   
		LOG.error(url);
		String mimeType = new MimetypesFileTypeMap().getContentType(f);
		String mediaType = "";
		if (mimeType == null) {
			mimeType = "text/plain";
		} else {
			mediaType = mimeType.split("/")[0].equals("image") ? "pic" : "doc";
		}
		LOG.error(mimeType);
		String lastModifieDate = new SimpleDateFormat("yyyy MM dd HH:mm:ss").format(new Date());
		long fileSize = f.length();
		String passTicket = (String) core.getLoginInfo().get("pass_ticket");
		String clientMediaId = String.valueOf(new Date().getTime())
				+ String.valueOf(new Random().nextLong()).substring(0, 4);
		String webwxDataTicket = MyHttpClient.getCookie("webwx_data_ticket");
		if (webwxDataTicket == null) {
			LOG.error("get cookie webwx_data_ticket error");
			return null;
		}

		Map<String, Object> paramMap = core.getParamMap();

		
		**paramMap.put("UploadType", 2);
		paramMap.put("BaseRequest", core.getParamMap().get("BaseRequest"));**
		**这里缺少参数**
		paramMap.put("ClientMediaId", clientMediaId);
		paramMap.put("TotalLen", fileSize);
		paramMap.put("StartPos", 0);
		paramMap.put("DataLen", fileSize);
		paramMap.put("MediaType", 4);
		
		**paramMap.put("FromUserName", core.getUserSelf().getString("UserName"));
		paramMap.put("ToUserName", userId);
		paramMap.put("FileMd5", getMd5ByFile(f));**
            **这里些参数也缺少**
		MultipartEntityBuilder builder = MultipartEntityBuilder.create();
		builder.setMode(HttpMultipartMode.BROWSER_COMPATIBLE);

		builder.addTextBody("id", "WU_FILE_0", ContentType.TEXT_PLAIN);
		builder.addTextBody("name", filePath, ContentType.TEXT_PLAIN);
		builder.addTextBody("type", mimeType, ContentType.TEXT_PLAIN);

		//builder.addTextBody("lastModifieDate", lastModifieDate, ContentType.TEXT_PLAIN);
**lastModifieDate 少了 一个字母d**
                **builder.addTextBody("lastModifiedDate", lastModifieDate, ContentType.TEXT_PLAIN);**
		builder.addTextBody("size", String.valueOf(fileSize), ContentType.TEXT_PLAIN);
		builder.addTextBody("mediatype", mediaType, ContentType.TEXT_PLAIN);
		builder.addTextBody("uploadmediarequest", JSON.toJSONString(paramMap), ContentType.TEXT_PLAIN);
		builder.addTextBody("webwx_data_ticket", webwxDataTicket, ContentType.TEXT_PLAIN);
		builder.addTextBody("pass_ticket", passTicket, ContentType.TEXT_PLAIN);
		builder.addBinaryBody("filename", f, ContentType.create(mimeType), new Date().getTime()+".jpg");
		HttpEntity reqEntity = builder.build();
		HttpEntity entity = myHttpClient.doPostFile(url, reqEntity);
		if (entity != null) {
			try {
				String result = EntityUtils.toString(entity, Consts.UTF_8);
				return JSON.parseObject(result);
			} catch (Exception e) {
				LOG.error("webWxUploadMedia 错误： ", e);
			}

		}
		return null;
	}

**Comment by fudanglp** [comment]
我这里发送图片也有问题
七月 01, 2017 7:43:23 下午 cn.zhouyafeng.itchat4j.utils.MyHttpClient doPostFile
信息: Certificate for <file.web.wechat.com> doesn't match any of the subject alternative names: [dev.wechat.com, file2.wechat.com, support.wechat.com, file.wechat.com, developers.wechat.com, admin.wechat.com, file1.wechat.com, api.wechat.com, help.wechat.com, video.wechat.com, compass.admin.wechat.com, wechat.com, www.wechat.com]

**Comment by yaphone** [comment]
图片格式需要jpg格式

**Comment by fudanglp** [comment]
jpg无误 @yaphone

**Comment by yaphone** [comment]
收到，我回去测试一下，多谢反馈

**Comment by fudanglp** [comment]
HttpClient设为不要verify hostname就可以了

	static {
		cookieStore = new BasicCookieStore();

		SSLContext sslContext = null;
		KeyStore trustStore=null;
		try {
			trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
			sslContext = SSLContexts.custom().useTLS().loadTrustMaterial(trustStore, new AnyTrustStrategy()).build();
		} catch (KeyStoreException e) {
			e.printStackTrace();
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		} catch (KeyManagementException e) {
			e.printStackTrace();
		}

		httpClient = HttpClients.custom()
				.setSSLContext(sslContext)
				.setSSLHostnameVerifier(new NoopHostnameVerifier())
				.setDefaultCookieStore(cookieStore)
				.build();

	}

**Comment by yaphone** [comment]
你好，朋友，我这里没有设置，发送图片没有出现同样的问题，可能和具体环境有关，待进一步跟踪，再次感谢反馈。

**Comment by fudanglp** [comment]
嗯，看别人提不提类似的issue吧，可能跟环境也有关系，不清楚。 不过这个应该是SSL引起的无误。

**Comment by yaphone** [comment]
好的，后面我来跟踪一下，祝使用愉快！
