### ISSUE TITLE
集成到Web后，警告内存泄露的问题

### ISSUE THREAD

**Issue by LAzyOnline** [yaphone/itchat4j#61]
您好，我将itchat4j集成到我的web项目中了，我在tomcat监听器里边启动的WeChat，目前只是调起和监听，暂未试用它（没有发送任何数据），当我的web接口被调用时（与itchat4j无关），会提示内存溢出的警告，并导致tomcat重新启动，从而需要重新登录微信。
报错信息如下：
警告: The web application [BttenRobot] appears to have started a thread named [Thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.net.SocketInputStream.socketRead0(Native Method)
 java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
 java.net.SocketInputStream.read(SocketInputStream.java:170)
 java.net.SocketInputStream.read(SocketInputStream.java:141)
 sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
 sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
 sun.security.ssl.InputRecord.read(InputRecord.java:532)
 sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
 sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
 sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
 org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
 org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
 org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
 org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
 org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
 org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
 org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
 org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
 org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
 org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
 org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
 org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
 org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
 org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
 org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
 org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
 org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
 cn.zhouyafeng.itchat4j.utils.MyHttpClient.doGet(MyHttpClient.java:115)
 cn.zhouyafeng.itchat4j.service.impl.LoginServiceImpl.syncCheck(LoginServiceImpl.java:643)
 cn.zhouyafeng.itchat4j.service.impl.LoginServiceImpl.access$100(LoginServiceImpl.java:53)
 cn.zhouyafeng.itchat4j.service.impl.LoginServiceImpl$1.run(LoginServiceImpl.java:253)
 java.lang.Thread.run(Thread.java:745)
八月 07, 2017 7:12:19 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads

请问，我需要怎么做，才能解决这个问题呢？

**Comment by yaphone** [comment]
收到，朋友，但是最近在忙别的事情，后面我会继续跟踪，多谢反馈？

**Comment by LAzyOnline** [comment]
好的，感谢您的关注！

**Comment by LAzyOnline** [comment]
您好，问题我已经找到了，是因为我在项目中动态保存了properties文件，导致tomcat自动重启了，后面在项目中碰到使用itchat4j的jar包时，handler不处理的问题，我将源码集成至我的项目中解决了问题！
