### ISSUE TITLE
iphone发过来的视频下载下来是空的

### ISSUE THREAD

**Issue by bearyue** [yaphone/itchat4j#66]
iphone微信直接发视频过来下载后，下载到空的，用win版来发就不会，请问是不是httpclient问题？还是说什么问题？

**Comment by bearyue** [comment]
win版发过来http response
HttpResponseProxy{HTTP/1.1 206 Partial Content [Connection: keep-alive, Content-Type: video/mp4, Content-Range: bytes 0-27471/27472, Accept-Ranges: bytes, Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT, ETag: 040d5-82f440-b66654492d689ed7e29a, Content-Length: 27472] ResponseEntityProxy{[Content-Type: video/mp4,Content-Length: 27472,Chunked: false]}}

iphone发过来http response
HttpResponseProxy{HTTP/1.1 200 OK [Connection: keep-alive, Content-Type: video/mp4, Content-Length: 0] [Content-Type: video/mp4,Content-Length: 0,Chunked: false]}

有大神遇到吗？

**Comment by bearyue** [comment]
这个问题貌似是微信问题，我登录web版微信，我自己iphone发的视频一样是播放不了的，说明那个链接本来就有问题吧。但是奇怪的是我用别人的iphone发，我自己能下载，web版也能播，奇怪了

**Comment by yaphone** [comment]
是的，朋友，这个问题可能和微信版本/ios版本有关，安卓系统发送的视频/语音消息也有同样的问题。
祝使用愉快！  ：）
