### ISSUE TITLE
获取群聊消息的group id，以及按group id发送群聊消息

### ISSUE THREAD

**Issue by samsongli** [yaphone/itchat4j#74]
第一次发issue，首先感谢这么好的代码！
我看了一下，代码结构很好，但是似乎没有找到BaseMsg中的group id，在MessageTools里面也没有找到向某个group发送消息的方法。我记得itchat中是有这两个功能的，不知是否没有实现。
再次感谢！

**Comment by samsongli** [comment]
搞明白了，谢谢！

**Comment by eimsteim** [comment]
我也遇到了相同的问题，请问是楼主是如何向群内发送消息的呢？
